# 1. 텍스트의 토큰화

In [1]:
from tensorflow.keras.preprocessing.text import text_to_word_sequence

text='해보지 않으면 해낼 수 없다.'
result=text_to_word_sequence(text)
print(result)

['해보지', '않으면', '해낼', '수', '없다']


In [2]:
from tensorflow.keras.preprocessing.text import Tokenizer

docs=['먼저 텍스트의 각 단어를 나누어 토큰화합니다.','텍스트의 단어를 토큰화해야 딥러닝에서 인식됩니다.','토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',]

token=Tokenizer()#토큰화 함수 지정
token.fit_on_texts(docs)#토큰화 함수에 문장 적용

print(token.word_counts)#단어의 빈도수를 계산한 결과를 출력

print(token.document_count)

OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 2), ('나누어', 1), ('토큰화합니다', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])
3


In [3]:
print(token.word_docs)
print(token.word_index)

defaultdict(<class 'int'>, {'나누어': 1, '각': 1, '토큰화합니다': 1, '단어를': 2, '텍스트의': 2, '먼저': 1, '토큰화해야': 1, '딥러닝에서': 2, '인식됩니다': 1, '토큰화한': 1, '사용할': 1, '결과는': 1, '수': 1, '있습니다': 1})
{'텍스트의': 1, '단어를': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '나누어': 6, '토큰화합니다': 7, '토큰화해야': 8, '인식됩니다': 9, '토큰화한': 10, '결과는': 11, '사용할': 12, '수': 13, '있습니다': 14}


## 주어진 문장을 단어로 토큰화 하기

In [ ]:
#텍스트 전처리 함수  text_to_word_sequence 호출
from tensorflow.keras.preprocessing.text import text_to_word_sequence

# 전처리 할 텍스트 정리
text='해보지 않으면 해낼 수 없다.'

#핵당 텍스트 토큰화
result=text_to_word_sequence(text)
print("\n원문:\n", text)
print("\n토큰화:\n", result)

#텍스트 전처리 함수 Tokenizer()호출
from tensorflow.keras.preprocessing.text import Tokenizer

#전처리하려는 세 개의 문장 정하기
docs=['먼저 텍스트의 각 단어를 나누어 토큰화합니다.',
      '텍스트의 단어를 토큰화해야 딥러닝에서 인식됩니다.',
      '토큰화한 결과는 딥러닝에서 사용할 수 있습니다.',]

#토큰화 함수를 이용해 전처리하는 과정
token=Tokenizer()#토큰화 함수 지정
token.fit_on_texts(docs)#토큰화 함수에 문장 적용

#각 옵션에 맍춰 단어의 빈도 수를 계산한 결과 출력
print("\n단어 카운트:\n", token.word_counts)

#출력된는 순서는 랜덤
print("\n문장 카운트:\n", token.document_count)
print("\n각 단어가 몇 개의 문장에 포함되어 있는가:\n", token.word_docs)
print("\n각 단어에 매겨진 인텍스 값:\n", token.word_index)


원문:
 해보지 않으면 해낼 수 없다.

토큰화:
 ['해보지', '않으면', '해낼', '수', '없다']

단어 카운트:
 OrderedDict([('먼저', 1), ('텍스트의', 2), ('각', 1), ('단어를', 2), ('나누어', 1), ('토큰화합니다', 1), ('토큰화해야', 1), ('딥러닝에서', 2), ('인식됩니다', 1), ('토큰화한', 1), ('결과는', 1), ('사용할', 1), ('수', 1), ('있습니다', 1)])

문장 카운트:
 3

각 단어가 몇 개의 문장에 포함되어 있는가:
 defaultdict(<class 'int'>, {'나누어': 1, '텍스트의': 2, '먼저': 1, '단어를': 2, '토큰화합니다': 1, '각': 1, '딥러닝에서': 2, '토큰화해야': 1, '인식됩니다': 1, '있습니다': 1, '결과는': 1, '토큰화한': 1, '수': 1, '사용할': 1})

각 단어에 매겨진 인텍스 값:
 {'텍스트의': 1, '단어를': 2, '딥러닝에서': 3, '먼저': 4, '각': 5, '나누어': 6, '토큰화합니다': 7, '토큰화해야': 8, '인식됩니다': 9, '토큰화한': 10, '결과는': 11, '사용할': 12, '수': 13, '있습니다': 14}


# 2. 단어의 원-핫 인코딩

In [4]:
text = ['오랫동안 꿈꾸는 이는 그 꿈을 닮아간다']

token = Tokenizer()
token.fit_on_texts(text)

print(token.word_index)

{'오랫동안': 1, '꿈꾸는': 2, '이는': 3, '그': 4, '꿈을': 5, '닮아간다': 6}


In [5]:
x = token.texts_to_sequences(text) # 각 토큰의 인덱스
print(x)

[[1, 2, 3, 4, 5, 6]]


In [6]:
from tensorflow.keras.utils import to_categorical

word_size = len(token.word_index)+1 # 각 배열 가장 앞에 0이 추가되므로 +1(파이썬의 인덱스는 0부터 시작하지만, 현재 토큰은 1부터 시작이기 때문)
x = to_categorical(x, # 원핫인코딩을 진행할 데이터 
                   num_classes=word_size) # 클래스의 개수

print(x)

[[[0. 1. 0. 0. 0. 0. 0.]
  [0. 0. 1. 0. 0. 0. 0.]
  [0. 0. 0. 1. 0. 0. 0.]
  [0. 0. 0. 0. 1. 0. 0.]
  [0. 0. 0. 0. 0. 1. 0.]
  [0. 0. 0. 0. 0. 0. 1.]]]


# 3.단어 임베딩

In [7]:
# 임베딩
# 단순한 원핫 인코딩은 결과가 sparse한 형태가 됨
# 이를 해결하기 위해 단어의 의미를 고려하여 좀 더 조밀한 차원에 단어를 벡터로 표현하는 것

# 임베딩에 입력될 단어 수 지정
word_size = len(token.word_index) +1 # 파이썬의 인덱스는 0부터 시작

# 4. 텍스트를 읽고 긍정, 부정 예측하기

## 영화 리부가 긍정적인지 부정적인지 예측하기

In [8]:
import numpy
import tensorflow as tf
from numpy import array
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten, Embedding

#텍스트 리뷰 자료 지정
docs=['너무 재밌네요','최고예요', '참 잘 만든 영화예요','추천하고 싶은 영화입니다.','한번 더 보고 싶네요.','글쎄요','별로예요','생각보다 지루하네요','연기가 어색해요','재미없어요']

#긍정 리뷰는 1 부정 리뷰는 0으로 클래스 지정
classes=array([1,1,1,1,1,0,0,0,0,0])

# 토큰화 
token = Tokenizer()
token.fit_on_texts(docs)
print(token.word_index)
x = token.texts_to_sequences(docs)
print("\n리뷰 텍스트, 토큰화 결과:\n",  x)

# 패딩, 서로 다른 길이의 데이터를 4로 맞추어 줍니다.
padded_x = pad_sequences(x, 4)  
print("\n패딩 결과:\n", padded_x)
 
#딥러닝 모델
print("\n딥러닝 모델 시작:")

#임베딩에 입력될 단어의 수를 지정합니다.
word_size = len(token.word_index) +1
 
#단어 임베딩을 포함하여 딥러닝 모델을 만들고 결과를 출력합니다.
model = Sequential()
model.add(Embedding(word_size, 8, input_length=4))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.fit(padded_x, classes, epochs=20)
print("\n Accuracy: %.4f" % (model.evaluate(padded_x, classes)[1]))

{'너무': 1, '재밌네요': 2, '최고예요': 3, '참': 4, '잘': 5, '만든': 6, '영화예요': 7, '추천하고': 8, '싶은': 9, '영화입니다': 10, '한번': 11, '더': 12, '보고': 13, '싶네요': 14, '글쎄요': 15, '별로예요': 16, '생각보다': 17, '지루하네요': 18, '연기가': 19, '어색해요': 20, '재미없어요': 21}

리뷰 텍스트, 토큰화 결과:
 [[1, 2], [3], [4, 5, 6, 7], [8, 9, 10], [11, 12, 13, 14], [15], [16], [17, 18], [19, 20], [21]]

패딩 결과:
 [[ 0  0  1  2]
 [ 0  0  0  3]
 [ 4  5  6  7]
 [ 0  8  9 10]
 [11 12 13 14]
 [ 0  0  0 15]
 [ 0  0  0 16]
 [ 0  0 17 18]
 [ 0  0 19 20]
 [ 0  0  0 21]]

딥러닝 모델 시작:
Epoch 1/20
1/1 [==============================] - 3s 3s/step - loss: 0.6942 - accuracy: 0.5000
Epoch 2/20
1/1 [==============================] - 0s 8ms/step - loss: 0.6920 - accuracy: 0.5000
Epoch 3/20
1/1 [==============================] - 0s 11ms/step - loss: 0.6898 - accuracy: 0.5000
Epoch 4/20
1/1 [==============================] - 0s 7ms/step - loss: 0.6876 - accuracy: 0.6000
Epoch 5/20
1/1 [==============================] - 0s 9ms/step - loss: 0.6855 - accuracy: 0.7000
Epoch 6/2